title: scoop-airgap
description: Airgapped Scoop package mirroring for enterprise environments
remote_theme: just-the-docs/just-the-docs@v0.10.0

url: "https://schraax.github.io"
baseurl: "/scoop-airgap"

# just-the-docs settings
color_scheme: light
search_enabled: true
heading_anchors: true

nav_sort: order   # use nav_order front matter

footer_content: "scoop-airgap — MIT License"

plugins:
  - jekyll-seo-tag
